name: consmed_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2
  decimal: ^2.3.3
  dio: ^5.7.0
  intl: ^0.18.1
  riverpod: ^2.6.1
  shared_preferences: ^2.2.3
  animate_do: ^3.3.4
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
